version: '3.7'

services:
  app:
    build: .
    container_name: event-booking-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./pom.xml:/app/pom.xml
    networks:
      - event-network
    # Commande à exécuter dans le conteneur de l'application
    command: ["java", "-Dspring.devtools.restart.enabled=true", "-jar", "/app/event-booking-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:13
    container_name: event-booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    networks:
      - event-network

networks:
  event-network:
    driver: bridge
